### ISSUE TITLE
Automate PyPi releases

### ISSUE THREAD

**Issue by ajbozarth** [Qiskit/qiskit-code-assistant-jupyterlab#17]
Currently we release on PyPi by having @cbjuan log into a specific admin account and publishing manually. We should set up an automated release process to push new releases to PyPi without needing to manual log into an admin account.

The JupyterLab extension template included support for the Jupyter Releaser, so we may be able to leverage that.

**Comment by cbjuan** [comment]
@y4izus, @jesus-talavera-ibm , can you work with @ajbozarth to automate the releases for the Qiskit Code Assitant JupyterLab extension?

**Comment by ajbozarth** [comment]
For reference, here's [a blog on the Jupyter releaser](https://blog.jupyter.org/automate-your-releases-with-the-jupyter-releaser-701e7b9841e6), the releaser GitHub Actions workflow is already included in the repo, so I believe all I need help with is plugging in the correct PyPi credentials. The key issue is what those credentials are.

**Comment by jesus-talavera-ibm** [comment]
Hi @ajbozarth, there is no need to include credentials in GitHub actions. You can grant GitHub to publish package from pypi side:![Image](https://github.com/user-attachments/assets/445af8a4-e2ca-42d7-9e91-0677175e3a0e)

Credentials for `ibm.q.widgets` are available in team's 1pass vault

For example, here is the configuration for qiskit-ibm-transpiler (you can also check it in `ibm.q.widgets` pypi account setting): 
![Image](https://github.com/user-attachments/assets/aa388758-2d56-40c9-bd45-9b0d7fad8b01)

**Comment by cbjuan** [comment]
@ajbozarth you should. In any case, let's review it in the next weeks.
